[build]
  publish = "frontend/dist"    # Path to your Vite build output
  functions = "backend/functions"  # Path to serverless functions

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200
